FROM node:18.19-bookworm

WORKDIR /app/
COPY controllers/ /app/controllers
COPY models/ /app/models
COPY routes/ /app/routes
COPY package.json /app/
COPY server.js /app/

RUN npm install

CMD ["npm", "start"]
